name: Feature branch workflow


on:
  push:
    branches:
      - "feature/*"

jobs:
   feature-test:
     runs-on: ubuntu-latest

     steps: 
      - name: checkout code
        uses: action/checkout@v3

      - name: run tests
        run: echo "running test from feature branch"
     
      
