name: Github Conditional workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test-conditionals:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions@checkout@v3

    - name: run test
      if: contains(github.event.pull_request.labels.*.name, 'run-tests')
      run: echo "Running tests"
